[workspace]
members = [
    "sim/spi_basic/test",
    "sim/spififo/test",
    "sim/sram32/test",
    "sim/i2s/test",
    "sim/spi_dopi/test",
    "sim/kbd/test",
    "sim/memlcd/test",
    "sim/template/test",
    "sim_support/rust/bios",
    "sim_support/rust/pac",
    "sim_support/rust/macros",
]
